### ISSUE TITLE
Issue with K-factor Calibration Tool

### ISSUE THREAD

**Issue by kendrickxy** [MarlinFirmware/MarlinDocumentation#532] opened 2023-12-05 00:34 UTC
When I enter a value that causes an error, the software won't let me generate the G-code, even after correction.
i.g:

<img width="452" alt="image" src="https://github.com/MarlinFirmware/MarlinDocumentation/assets/16179839/ce98fec3-8622-4032-8df1-9961baefc333">

<img width="632" alt="image" src="https://github.com/MarlinFirmware/MarlinDocumentation/assets/16179839/d97cd6be-34e8-4760-a91e-2fae6b54de5b">

I get this error. So I change the K-Factor Stepping to 0.002, but I'm still unable to generate the G-code.

The only solution I've found is to reload the page and enter the data once again.

**Comment by kendrickxy** [comment] 2023-12-05 00:37
Well I guess changing the html code is also a work around 😄

**Comment by thisiskeithb** [comment] 2023-12-05 00:48
The form doesn't re-validate settings until you tab/click into another textbox.

**Comment by kendrickxy** [comment] 2023-12-09 10:44
I've tried, Textbox, Dropbox, checkbox. Unfortunately doesn't fix the Generate button

**Comment by thisiskeithb** [comment] 2023-12-09 10:59
Which OS & browser are you using?

**Comment by thinkyhead** [comment] 2023-12-12 06:36
Unable to reproduce…
<img width="353" alt="image" src="https://github.com/MarlinFirmware/MarlinDocumentation/assets/698003/561631de-cd4b-463f-b02d-23802392eb9f">

Floating point maths can sometimes be imprecise. So it's possible the test for even divisibility fails on some devices with wonky math libraries. Try different browsers and operating systems to see if they do the same thing. Meanwhile, we can try adjusting this test to see if adding `parseInt` or other tricks help.

**Comment by kendrickxy** [comment] 2023-12-12 19:15
I am using Edge, but in the video I tried Chrome.

https://github.com/MarlinFirmware/MarlinDocumentation/assets/16179839/5db2609e-05cd-405a-881a-465f2d52b322

Am I doing it wrong?

**Comment by thinkyhead** [comment] 2024-01-05 23:00
The buttons should be fixed now.

**Closed by thinkyhead** 2024-01-05 23:00 UTC
Labels: Bug / Fix
